apps/weather_api/urls.py
from django.urls import path

from . import views


app_name = "weather"

urlpatterns = [
    path("", views.Weather.as_view(), name="index"),
    path("clear_session", views.clear_session, name="clear_session"),
    path("api_get", views.WeatherApi.as_view(), name="api_get"),
    path("api_get_detail/<str:city>", views.WeatherDetailApi.as_view(), name="api_get_detail"),
    path("city_information", views.WeatherCity.as_view(), name="city_information"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.weather_api.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

apps/weather_api/views.py
from django.views.generic import TemplateView, DeleteView
from django.shortcuts import render
from django.http import JsonResponse
from .constants import WEATHER_GIFS, ERRORS

from django.conf import settings

from django.views.decorators.http import require_http_methods

import requests
import json


class TemplateMixin(TemplateView):
    def setup(self, request, *args, **kwargs):
        """
        Setup if the request is htmx
        """
        super().setup(request, *args, **kwargs)
        self.is_htmx = request.headers.get("HX-Request") == "true"

    def trigger_error_response(self, message):
        """
        Send error response
        """
        return JsonResponse({"message": message}, status=400)


class Weather(TemplateMixin):
    template_name = "weather/index.html"


class WeatherApi(TemplateMixin):
    template_name = "weather/city.html"

    def get(self, *args, **kwargs):
        if self.is_htmx:
            city_name = self.request.GET.get("q")

            if "cities" not in self.request.session.keys():
                self.request.session["cities"] = []

            if city_name in self.request.session["cities"]:
                return self.trigger_error_response("The city is already in the list")

            response = requests.get(
                f"{settings.WEATHER_API_BASE_URL}?access_key={settings.WEATHER_API_ACCESS_KEY}&query={city_name}"
            )
            response_json = response.json()

            if "error" in response_json.keys():
                error_code = response_json.get("error").get("code")
                error_message = ERRORS[error_code]
                return self.trigger_error_response(error_message)

            self.request.session["cities"].append(city_name)
            self.request.session.save()

            context = {
                "response": json.dumps(response_json),
                "city": city_name,
                "id": city_name.replace(" ", "_").replace(",", "_"),
            }
            return render(self.request, "weather/city.html", context)
        return super().get(*args, **kwargs)


class WeatherDetailApi(DeleteView):
    def delete(self, request, *args, **kwargs):
        self.request.session["cities"].remove(kwargs.get("city"))
        self.request.session.save()
        return JsonResponse({}, status=204)


class WeatherCity(TemplateMixin):
    template_name = "weather/information.html"

    def get(self, *args, **kwargs):
        if self.is_htmx:
            city_info = json.loads(self.request.GET.get("city_info"))
            try:
                city_info["gif"] = WEATHER_GIFS[city_info.get("current").get("weather_descriptions")[0]]
            except KeyError:
                city_info["gif"] = "sunny.svg"

            context = {"response": city_info}
            return render(self.request, "weather/information.html", context)
        return super().get(*args, **kwargs)


@require_http_methods(["POST"])
def clear_session(request):
    if "cities" in request.session.keys():
        del request.session["cities"]
        request.session.save()
    return JsonResponse({}, status=204)

apps/weather_api/templates/weather/index.html
{% extends "base.html" %}
{% load static %}

{% block main %}
<section class='col centered px-2 lg:px-60 mt-6'>
        <h1 class="text-4xl font-extrabold leading-none tracking-tight text-BLUE_DARKER md:text-5xl lg:text-6xl text-center">WeatherApp</h1>
        {% comment %} <---- Search input ----> {% endcomment %}
        <form id="search-city" 
            hx-get="{% url 'weather:api_get' %}" 
            hx-trigger="submit" 
            hx-target="#list-cities" 
            hx-swap="beforeend"
            class="flex w-full mt-6"
            hx-indicator="#loading">
            <div class="relative w-full border-BLUE_DARK border-[1px] rounded-md shadow-md">
                <div class="absolute inset-y-0 w-full left-0 flex items-center pl-3 pointer-events-none">
                    <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
                </div>
                <input name="q" id="default-search"
                class="w-full focus:outline-none px-10 py-4 text-BLUE_DARKER placeholder:text-GRAY_MEDIUM placeholder:font-thin rounded-md font-bold"
                placeholder="Search for city or country..."
                required>
                <button type="submit" class="search-button">Search</button>
            </div>
        </form>
    </section>
    <section class='col items-center h-4/5 px-2 lg:px-60'>
        <i class="absolute top-[5px] left-[8px] w-8 z-10 md:hidden" _="on click toggle .hidden on #list-cities then toggle .hidden on <img/> in me">
            <img src="{% static 'images/svg/menu-hamburger.svg' %}" />
            <img class="top-[5px] left-[8px] ml-1 mt-1 fixed hidden" src="{% static 'images/svg/x-symbol.svg' %}" />
        </i>
        <div id="error-section" class="col w-auto">

        </div>
        {% comment %} <---- Weather Section ----> {% endcomment %}
        {% comment %} <h1 class="my-4 text-4xl font-extrabold leading-none tracking-tight text-BLUE_DARKER md:text-5xl lg:text-6xl">WeatherApp</h1> {% endcomment %}
        <div class="row m-2 w-full bg-white h-[80vh] border-BLUE_DARK border-[1px] rounded-md shadow-md !bg-[transparent] md:h-4/5">
            <div id="list-cities" class="fixed hidden top-0 left-0 w-4/5 h-full md:relative md:flex md:col md:w-1/3 md:p-3 md:pr-0 md:pl-0 bg-BLUE_DARK">
                <div class="row justify-center pl-3">
                    <h4 class="mb-0 p-2 text-xl font-bold text-WHITE">MY CITIES</h4>
                    {% comment %} <button class="bg-BLUE_LIGHT rounded-tl-lg rounded-tr-lg mb-0 p-2 focus:ring-4 focus:outline-none focus:ring-BLUE_MEDIUM">Favorites</button> {% endcomment %}
                </div>
            </div>
            <div id="city-information" class="col w-full">

            </div>
        </div>
    </section>
{% endblock %}

templates/base.html
{% load static tailwind_tags %}
<html>
    <head>
        <title>Weather App</title>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta http-equiv="X-UA-Compatible" content="ie=edge">
            {% tailwind_css %}
        </head>
  <body
    class="bg-WHITE leading-normal full tracking-normal h-[110vh]"
    style="background: linear-gradient(180deg, rgba(255,255,255,1) 0%, rgba(234,252,255,1) 100%);"
    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
    hx-post="{% url 'weather:clear_session' %}" 
    hx-trigger="load delay:0.5s"
    >
    <div id="loading" class="loading">
      <img id="loading-image" src="{% static 'gifs/loader.gif' %}" alt="Loading..." />
    </div>
    <main class="full">
      {% block main %}{% endblock %}
      <div class='float-message'>
          <span></span>
      </div>
    </main>

    <script src="https://unpkg.com/htmx.org@1.1.0"></script>
    <script src="https://unpkg.com/hyperscript.org@0.9.8"></script>
    {% block extra_js %}{% endblock %}
    <script>

      document.body.addEventListener('htmx:configRequest', () => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      });

      // Check in every request if the response is an error, and show the message
      document.body.addEventListener('htmx:responseError', (evt) => {
        if(evt.detail.xhr.status == 400){
          let messsage = JSON.parse(evt.detail.xhr.response).message;
          showErrorMessage(messsage, 'error');
          evt.preventDefault();
          evt.stopPropagation();
        }
      });

      const showErrorMessage = (message, type) => {
        // show message, error or success
          var messageContainer = document.getElementsByClassName("float-message");
          var messageHtml = messageContainer[0];
          messageHtml.querySelectorAll('span')[0].innerHTML = message;
          messageHtml.classList.toggle('show');
          messageContainer[0].classList.add(`float-message-${type}`);
          setTimeout(function(){ messageContainer[0].classList.toggle('show'); }, 5000);
      };

    </script>
  </body>
</html>